#version: '3'
services:

  ace-db-prod:
    image: mysql:8.0
    container_name: ace-db-prod
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1999asheron2017
      - MYSQL_USER=acedockeruser
      - MYSQL_PASSWORD=2020acEmulator2017
      - MYSQL_DATABASE=ace%
      - TZ=America/New_York
    volumes:
      - C:\ACE\db-data-prod:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: acemulator/ace:prod
    depends_on:
      ace-db-prod:
        condition: service_healthy
    container_name: ace-server-prod
    environment:
      - ACE_WORLD_NAME=Thresholme
      - ACE_DAT_FILES_DIRECTORY=/ace/Dats
      - ACE_SQL_AUTH_DATABASE_NAME=ace_auth
      - ACE_SQL_AUTH_DATABASE_HOST=ace-db-prod
      - ACE_SQL_AUTH_DATABASE_PORT=3306
      - ACE_SQL_SHARD_DATABASE_NAME=ace_shard
      - ACE_SQL_SHARD_DATABASE_HOST=ace-db-prod
      - ACE_SQL_SHARD_DATABASE_PORT=3306
      - ACE_SQL_WORLD_DATABASE_NAME=ace_world
      - ACE_SQL_WORLD_DATABASE_HOST=ace-db-prod
      - ACE_SQL_WORLD_DATABASE_PORT=3306
      - ACE_SQL_INITIALIZE_DATABASES=true
      - ACE_SQL_DOWNLOAD_LATEST_WORLD_RELEASE=true
      - ACE_NONINTERACTIVE_SETUP=true
      - TZ=America/New_York
    volumes:
      - C:\ACE\Content:/ace/Content
      - C:\ACE\Dats:/ace/Dats
      - C:\ACE\Logs-prod:/ace/Logs
      - C:\ACE\Mods:/ace/Mods
    ports:
      - "9000-9001:9000-9001/udp"
    stdin_open: true
    restart: unless-stopped
