#version: '3'
services:

  ace-db-dev:
    image: mysql:8.0
    container_name: ace-db-dev
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1999asheron2017
      - MYSQL_USER=acedockeruser
      - MYSQL_PASSWORD=2020acEmulator2017
      - MYSQL_DATABASE=ace%
      - TZ=America/New_York
    volumes:
      - C:\ACE\db-data-dev:/var/lib/mysql
    ports:
      - "3307:3306/tcp"  # Different port to avoid conflict with prod
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: acemulator/ace:dev
    depends_on:
      ace-db-dev:
        condition: service_healthy
    container_name: ace-server-dev
    environment:
      - ACE_WORLD_NAME=Thresholme-Dev
      - ACE_DAT_FILES_DIRECTORY=/ace/Dats
      - ACE_SQL_AUTH_DATABASE_NAME=ace_auth
      - ACE_SQL_AUTH_DATABASE_HOST=ace-db-dev
      - ACE_SQL_AUTH_DATABASE_PORT=3306
      - ACE_SQL_SHARD_DATABASE_NAME=ace_shard
      - ACE_SQL_SHARD_DATABASE_HOST=ace-db-dev
      - ACE_SQL_SHARD_DATABASE_PORT=3306
      - ACE_SQL_WORLD_DATABASE_NAME=ace_world
      - ACE_SQL_WORLD_DATABASE_HOST=ace-db-dev
      - ACE_SQL_WORLD_DATABASE_PORT=3306
      - ACE_SQL_INITIALIZE_DATABASES=true
      - ACE_SQL_DOWNLOAD_LATEST_WORLD_RELEASE=true
      - ACE_NONINTERACTIVE_SETUP=true
      - TZ=America/New_York
    volumes:
      - C:\ACE\Content:/ace/Content
      - C:\ACE\Dats:/ace/Dats
      - C:\ACE\Logs-dev:/ace/Logs
      - C:\ACE\Mods:/ace/Mods
    ports:
      - "9002-9003:9000-9001/udp"  # Map to different external ports
    stdin_open: true
    restart: on-failure
